### ISSUE TITLE
After version 0.9.1 I can't connect

### ISSUE THREAD

**Issue by thelinuxlich** [thunks/thunk-redis#5]
A simple redis.createClient(port, host) is giving:

```
thunk-redis [TypeError: Cannot read property 'push' of null]
/app/releases/20150428184526/node_modules/thunk-redis/lib/connection.js:272
      var command = reply.commands.first();
                         ^
TypeError: Cannot read property 'commands' of null
    at Resp.<anonymous> (/app/releases/20150428184526/node_modules/thunk-redis/lib/connection.js:272:26)
    at emitOne (events.js:77:13)
    at Resp.emit (events.js:166:7)
    at Resp.feed (/app/releases/20150428184526/node_modules/thunk-redis/node_modules/respjs/index.js:73:10)
    at Socket.<anonymous> (/app/releases/20150428184526/node_modules/thunk-redis/lib/connection.js:136:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at readableAddChunk (_stream_readable.js:145:16)
    at Socket.Readable.push (_stream_readable.js:109:10)
    at TCP.onread (net.js:508:20)
```

**Comment by zensh** [comment]
Sorry, I published a develop branch to npm, it is not really the v0.9.1.
I have taged v0.9.2 and published it to npm now~

**Comment by Ace80** [comment]
thunk-redis [TypeError: Cannot read property 'push' of null]
/app/releases/20150428184526/node_modules/thunk-redis/lib/connection.js:272
      var command = reply.commands.first();

**Comment by Ace80** [comment]
TypeError: Cannot read property 'commands' of null
    at Resp.<anonymous> (/app/releases/20150428184526/node_modules/thunk-redis/lib/connection.js:272:2
