### ISSUE TITLE
thunk-redis Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by meteormatt** [thunks/thunk-redis#9]
想问下出现 `thunk-redis Error: connect ECONNREFUSED`是什么原因?
Redis是cluster模式

代码如下
https://gist.github.com/meteormatt/33f8fcd231e32cea4cb8

错误信息如下

``` bash
redis connected!
thunk-redis Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
thunk-redis Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
thunk-redis Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
redis server info: { redis_version: '3.0.0',
  redis_git_sha1: '00000000',
  redis_git_dirty: '0',
  redis_build_id: '692093c2a00c8ba5',
  redis_mode: 'cluster',
  os: 'Linux 3.2.0-60-generic x86_64',
  arch_bits: '64',
  multiplexing_api: 'epoll',
  gcc_version: '4.6.3',
  process_id: '26299',
  run_id: '6b7a05dbb908c1e1c902aa58de97f46e98338d91',
  tcp_port: '6380',
  uptime_in_seconds: '2767678',
  uptime_in_days: '32',
  hz: '10',
  lru_clock: '5614127',
  config_file: '/etc/redis/6380.conf' }
current database size: 0
thunk-redis Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

![错误截图](https://cloud.githubusercontent.com/assets/424475/7649394/331cde62-fb1f-11e4-8c3e-ed6a0420e214.png)

**Comment by zensh** [comment]
redis server 关闭了就会出现这个错误，你可以用 `./redis-cli -p 6379` 试一试能不能连上。
另外 `select` 不能在 cluster 中使用，会报错的

**Comment by zensh** [comment]
目前能连上的是 6380，你可以用 `./redis-cli -p 6380 cluster nodes` 试一试当前的节点状态

**Comment by meteormatt** [comment]
cluster状态是这样的.

``` bash
~$ redis-cli -h 42.121.14.192 -p 6380 cluster nodes
0408b629bb96d97101eb276a5e80b31992986387 127.0.0.1:6380 myself,master - 0 0 2 connected 5461-10922
99c388fcc0ffce74200eb6c66feceffa162a0012 127.0.0.1:6381 master - 0 1431681027020 3 connected 10923-16383
a7afbc31454465663c24ad9a0736cef9cc8522d4 127.0.0.1:6379 master - 0 1431681025016 1 connected 0-5460
```

**Comment by zensh** [comment]
远程机吗？是不是另外两个端口没有对外开放？`redis-cli` 能连上应该就能连上的

**Comment by meteormatt** [comment]
是服务器上的. `redis-cli`都可以连上的.

**Comment by zensh** [comment]
`redis-cli -h 42.121.14.192 -p 6380 cluster slots` 呢

我大概知道原因了，应该是 cluster slots 返回的节点 IP 是 `127.0.0.1:6381`，而不是 `42.121.14.192`，所以 client 会尝试连接  `127.0.0.1:6381`，自然报错，但实际上 cluster 已经正常连接，这 bug 我会尽快修复。

**Comment by zensh** [comment]
先 删掉 https://github.com/thunks/thunk-redis/blob/master/lib/connection.js#L393 393和394行，应该就正常了

**Comment by meteormatt** [comment]
恩. 先去掉那2行就不报错了.

**Comment by zensh** [comment]
另外要注意的是 cluster 有些命令不能用了如 `select`，还有些命令如 `multi` 在cluster 模式下要这样写：

``` js
this.multi('key'),
this.set('key', 'key'),
this.get('key'),
this.exec('key')
```

确保 `multi` 和 `exec` 请求发送到了同一个节点

**Comment by zensh** [comment]
这种 bug 应该属于 redis 的 bug，cluster slots 或 cluster nodes 应该告诉我真实的链接 IP 的，而不是 `127.0.0.1`

**Comment by meteormatt** [comment]
恩. 可能是我们cluster建的有问题.

**Comment by zensh** [comment]
我这边使用远程 redis cluster 测试了下，能返给我真实 IP 啊。你是怎么配置的~

**Comment by zensh** [comment]
修复了一下，发现 IP 不正确时不会自动连接

**Comment by meteormatt** [comment]
我来问一下同事.
Redis是他搭建的.
但是他用PHP的库都是可以正常连接的.

**Comment by zensh** [comment]
因为 thunk-redis 有自动连接策略，当发现连接到 cluster 时，会通过 cluster slots 获取集群信息，通过获取到的信息连接其它节点，也就是通常只需要告诉 thunk-redis 一个节点就行了。

现在你们的 cluster slots 返回了的节点信息 IP 不对。

**Comment by meteormatt** [comment]
改成现在这个样子后就没有问题了.

``` bash
42.121.14.192:6380> cluster nodes
547ac3b55407c4a81e637c6eb51bfc586549c941 42.121.14.192:6381 master - 0 1432117077166 3 connected 10923-16383
e0a6f0292041c6b0f2caf2d112a3db59d7c77618 42.121.14.192:6380 myself,master - 0 0 2 connected 5461-10922
68fb81f5ead44597c9f46cf346806eddf23ee59c 42.121.14.192:6379 master - 0 1432117076164 1 connected 0-5460
```
